// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
// import { defineConfig } from "@prisma/client";


if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL is not defined");
}

export default defineConfig({
  datasource: {
    // adapter: "node-postgres",
    url: process.env.DATABASE_URL,
  },
});



