// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL is not defined");
}

export default defineConfig({
  datasource: {
    url: process.env.DATABASE_URL,
   shadowDatabaseUrl: "postgresql://valentines_user:ryangates@localhost:5432/valentines_shadow",
  },
});



